# Настройки сервера
server:
  port: 8081

# Настройки приложения
spring:
  application:
    name: currency-service

  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
        register: true
        instance-host: localhost
        instance-port: ${server.port}

# Настройки логирования
logging:
  level:
    com.example: INFO
    org.springframework.web: WARN
    org.apache.zookeeper: WARN
    org.springframework.cloud.zookeeper: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"